import { useEffect, useMemo, useState } from 'react';

const roles = ['user', 'super-user', 'admin'];
const stamp = (value) => value ? new Intl.DateTimeFormat([], { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(Number(value))) : '—';

export default function AccessSettings({ section, permissions: initialPermissions = [], token, username, role, onSaved }) {
  const [users, setUsers] = useState([]); const [permissions, setPermissions] = useState(initialPermissions); const [dialog, setDialog] = useState(null); const [openUserMenu, setOpenUserMenu] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const request = async (path, options = {}) => { const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok || body.ok === false) throw new Error(body.message || 'Unable to save changes.'); return body.data; };
  const loadUsers = async () => { setBusy(true); setError(''); try { setUsers((await request('/api/data/users/list')).sort((a, b) => a.id.localeCompare(b.id))); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  useEffect(() => { if (section === 'users') loadUsers(); }, [section]); useEffect(() => setPermissions(initialPermissions), [initialPermissions]);
  const changed = useMemo(() => JSON.stringify(permissions.map(({ action, roles: allowed }) => ({ action, roles: allowed }))) !== JSON.stringify(initialPermissions.map(({ action, roles: allowed }) => ({ action, roles: allowed }))), [permissions, initialPermissions]);
  const canManage = (user) => username === 'dev' || (role === 'admin' && !['dev', 'admin'].includes(user.id));
  const toggle = (action, selected, all) => setPermissions((items) => items.map((permission) => { if (permission.action !== action) return permission; const allowed = permission.roles || []; const next = all ? (allowed.length >= roles.length ? [] : roles) : (allowed.includes(selected) ? allowed.filter((item) => item !== selected) : [...allowed, selected]); return { ...permission, roles: roles.filter((item) => next.includes(item)) }; }));
  const savePermissions = async () => { setBusy(true); setError(''); try { await request('/api/data/permissions/update', { method: 'POST', body: JSON.stringify(permissions.map((item, index) => ({ action: item.action, roles: item.roles || [], order: item.order ?? item.displayOrder ?? index }))) }); onSaved(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const saveUser = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const id = String(form.get('id') || '').trim().toLowerCase(); const selectedRole = String(form.get('role') || ''); const password = String(form.get('password') || ''); if (!id || !selectedRole || ((dialog.kind === 'add' || dialog.kind === 'password') && !password)) return; setBusy(true); setError(''); try { if (dialog.kind === 'add') await request('/api/data/user/add', { method: 'POST', body: JSON.stringify({ id, role: selectedRole, password }) }); if (dialog.kind === 'edit') await request('/api/data/user/update', { method: 'POST', body: JSON.stringify({ userId: id, role: selectedRole }) }); if (dialog.kind === 'password') await request('/api/data/user/resetPassword', { method: 'POST', body: JSON.stringify({ userId: id, password }) }); setDialog(null); await loadUsers(); onSaved(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); setError(''); try { await request('/api/data/user/remove', { method: 'POST', body: JSON.stringify({ userId: dialog.user.id }) }); setDialog(null); await loadUsers(); onSaved(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  if (section === 'permissions') return <div className="area-editor access-editor"><div className="area-editor-heading"><div><h3>Permission matrix</h3><p>Choose which roles can perform each action.</p></div><button className="small-primary" disabled={busy || !changed} onClick={savePermissions}>Save changes</button></div><div className="access-table"><div className="access-row access-head"><b>Action</b>{roles.map((item) => <b key={item}>{item === 'super-user' ? 'Super user' : item}</b>)}<b>All</b></div>{permissions.slice().sort((a, b) => (a.order ?? a.displayOrder ?? 0) - (b.order ?? b.displayOrder ?? 0)).map((permission) => { const allowed = permission.roles || []; return <div className="access-row" key={permission.action}><span>{permission.action}</span>{roles.map((item) => <label className="access-check" key={item}><input type="checkbox" checked={allowed.includes(item)} disabled={busy} onChange={() => toggle(permission.action, item)} /></label>)}<label className="access-check"><input type="checkbox" checked={roles.every((item) => allowed.includes(item))} disabled={busy} onChange={() => toggle(permission.action, null, true)} /></label></div>; })}</div>{error && <p className="form-error">{error}</p>}</div>;
  return <div className="area-editor access-editor"><div className="area-editor-heading"><div><h3>Manage users</h3><p>Assign roles, change passwords, and remove accounts.</p></div><button className="small-primary" disabled={busy} onClick={() => setDialog({ kind: 'add' })}>+ Add user</button></div><div className="access-table users-table"><div className="access-row access-head"><b>User</b><b>Role</b><b>Updated</b><b /></div>{users.map((user) => <div className="access-row" key={user.id}><b>{user.id}</b><span>{user.role}</span><span>{stamp(user['update-date'] ?? user.updateDate)}</span><div className="user-actions">{canManage(user) && <div className="gong-menu"><button className="menu-trigger" type="button" disabled={busy} aria-label={`Actions for ${user.id}`} onClick={() => setOpenUserMenu(openUserMenu === user.id ? null : user.id)}>•••</button>{openUserMenu === user.id && <div className="menu-popover"><button type="button" onClick={() => { setOpenUserMenu(null); setDialog({ kind: 'edit', user }); }}>Edit</button><button type="button" onClick={() => { setOpenUserMenu(null); setDialog({ kind: 'password', user }); }}>Change password</button><button className="menu-delete" type="button" onClick={() => { setOpenUserMenu(null); setDialog({ kind: 'remove', user }); }}>Delete</button></div>}</div>}</div></div>)}</div>{error && <p className="form-error">{error}</p>}{dialog && <div className="modal-backdrop nested-modal" role="presentation" onMouseDown={!busy ? () => setDialog(null) : undefined}><section className="confirm-modal area-form-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}>{dialog.kind === 'remove' ? <><p className="eyebrow">REMOVE USER</p><h2>Delete {dialog.user.id}?</h2><p>This account will no longer be able to sign in.</p><footer><button className="cancel-button" disabled={busy} onClick={() => setDialog(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={remove}>{busy ? 'Deleting…' : 'Delete user'}</button></footer></> : <><p className="eyebrow">USERS</p><h2>{dialog.kind === 'add' ? 'Add user' : dialog.kind === 'edit' ? 'Update user' : 'Change password'}</h2><form onSubmit={saveUser}><label>User ID<input name="id" autoFocus defaultValue={dialog.user?.id || ''} disabled={dialog.kind !== 'add'} required /></label><label>Role<select name="role" defaultValue={dialog.user?.role || 'user'} disabled={dialog.kind === 'password'}>{roles.map((item) => <option value={item} key={item}>{item}</option>)}</select></label>{dialog.kind !== 'edit' && <label>Password<input name="password" type="password" autoComplete="new-password" required /></label>}<footer><button className="cancel-button" type="button" disabled={busy} onClick={() => setDialog(null)}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save'}</button></footer></form></>}</section></div>}</div>;
}
